version: "3"
services:
  nats-streaming-1:
    command:
      - "-D"
      - "-p"
      - "4222"
      - "-m"
      - "8222"
      - "-store"
      - "file"
      - "-dir"
      - "datastore"
      - "-clustered"
      - "-cluster_node_id=node-1"
      - "-cluster=nats://0.0.0.0:6222"
      - "-cluster_peers=node-1,node-2,node-3"
      - "-routes"
      - "nats://nats-streaming-1:6222,nats://nats-streaming-2:6222,nats://nats-streaming-3:6222"
    expose:
      - "6222"
    image: "nats-streaming"
    ports:
      - "14222:4222"
      - "8222:8222"
  nats-streaming-2:
    command:
      - "-D"
      - "-p"
      - "4222"
      - "-store"
      - "file"
      - "-dir"
      - "datastore"
      - "-clustered"
      - "-cluster_node_id=node-2"
      - "-cluster_peers=node-1,node-2,node-3"
      - "-cluster=nats://0.0.0.0:6222"
      - "-routes"
      - "nats://nats-streaming-1:6222,nats://nats-streaming-2:6222,nats://nats-streaming-3:6222"
    image: "nats-streaming"
    expose:
      - "6222"
    ports:
      - "24222:4222"
  nats-streaming-3:
    command:
      - "-D"
      - "-p"
      - "4222"
      - "-store"
      - "file"
      - "-dir"
      - "datastore"
      - "-clustered"
      - "-cluster_node_id=node-3"
      - "-cluster=nats://0.0.0.0:6222"
      - "-cluster_peers=node-1,node-2,node-3"
      - "-routes"
      - "nats://nats-streaming-1:6222,nats://nats-streaming-2:6222,nats://nats-streaming-3:6222"
    image: "nats-streaming"
    expose:
      - "6222"
    ports:
      - "34222:4222"